### ISSUE TITLE
codesign error when using apple_resource_group

### ISSUE THREAD

**Issue by joprice** [bazelbuild/rules_apple#1019]
I am getting the error below when building an app that uses apple_resource_group:

```nd-sign-2048736916.sh failed: error executing command bazel-out/applebin_ios-ios_x86_64-fastbuild-ST-c4cf2ec641b4/bin/ios-app/ios-app-intermediates/process-and-sign-2048736916.sh should_sign
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_josephprice/33e38ece9d552fdf1983387d9ac53815/execroot/__main__/bazel-out/host/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 301, in <module>
    sys.exit(main(generate_arg_parser().parse_args()))
  File "/private/var/tmp/_bazel_josephprice/33e38ece9d552fdf1983387d9ac53815/execroot/__main__/bazel-out/host/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 296, in main
    _invoke_codesign(args.codesign, identity, args.entitlements, args.force,
  File "/private/var/tmp/_bazel_josephprice/33e38ece9d552fdf1983387d9ac53815/execroot/__main__/bazel-out/host/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 74, in _invoke_codesign
    _, stdout, stderr = execute.execute_and_filter_output(cmd,
  File "/private/var/tmp/_bazel_josephprice/33e38ece9d552fdf1983387d9ac53815/execroot/__main__/bazel-out/host/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/wrapper_common/execute.py", line 106, in execute_and_filter_output
    raise subprocess.CalledProcessError(proc.returncode, cmd_args)
subprocess.CalledProcessError: Command '['/usr/bin/codesign', '-v', '--sign', '-', '--force', '--timestamp=none', 'bazel-out/applebin_ios-ios_x86_64-fastbuild-ST-c4cf2ec641b4/bin/ios-app/ios-app_archive-root/Payload/ios-app.app']' returned non-zero exit status 1.
```

Adding `codesignopts = ["--deep"],` to `ios_application` allows it to build, but then when running the following error is throw in installation:

```
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain CFBundleVersion.
Ensure your bundle contains a CFBundleVersion.
```

I modified the tutorial ios app to reproduce this:

```python
load("@rules_cc//cc:defs.bzl", "objc_library")
  load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")
  load("@build_bazel_rules_apple//apple:resources.bzl", "apple_resource_group")

  apple_resource_group(
      name = "resources",
      structured_resources = glob([
        "resources/*",
        "resources/**/*",
      ]),
    )

  objc_library(
      name = "UrlGetClasses",
      srcs = [
          "UrlGet/AppDelegate.m",
          "UrlGet/UrlGetViewController.m",
          "UrlGet/main.m",
      ],
      hdrs = glob(["UrlGet/*.h"]),
      data = ["resources"],
  )

  ios_application(
      name = "ios-app",
      bundle_id = "Google.UrlGet",
      families = [
          "iphone",
          "ipad",
      ],
      infoplists = [":UrlGet/UrlGet-Info.plist"],
      launch_storyboard = "UrlGet/UrlGetViewController.xib",
      minimum_os_version = "8.0",
      visibility = ["//visibility:public"],
      deps = [":UrlGetClasses"],
      codesignopts = ["--deep"],
  )
```

Am I misuing `apple_resource_group` or is there some kind of conflict with the main Info.plist when resources are merged?

**Comment by thii** [comment]
Would it work if you rename the directory to something else? `Resources` is a reserved directory name—you can't add a custom directory with the same name.

**Comment by joprice** [comment]
Using a different name does work. It is a bit odd that you'd have to change the project to fit this situation though. I tried adding the Info.plist to the plists of that group, but that doesn't work either. Could the rule throw if the folder is named resources?

**Comment by thii** [comment]
At least it's documented. But yeah probably it'd be nicer if we could verify it instead of just letting it fail with an unrelated error. 

https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW13

> Note: An iOS app bundle cannot include a custom folder named “Resources.”

**Comment by keith** [comment]
Does Xcode do anything for this?

**Comment by thii** [comment]
Looks like there's already a validation here, it's just not checking all other case-insensitive variants of `Resources`.

https://github.com/bazelbuild/rules_apple/blob/8f60c52af7b04dc02ec688176d95e488272c3c73/apple/internal/processor.bzl#L117-L129
