### ISSUE TITLE
static/dynamic prebuilt import broken

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_apple#1033]
It seems that static/dynamic import is broken since https://github.com/bazelbuild/rules_apple/commit/572aee29236aa6aa850484d5706b79aa2a098219.

```
ERROR: /Users/steeve/code/xxx/BUILD.bazel:4:14: in @build_bazel_rules_apple//apple/internal/aspects:swift_dynamic_framework_aspect.bzl%swift_dynamic_framework_aspect aspect on swift_library rule //XXX:XXX:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_steeve/b4a34956aa658299157bf277e2fcd081/external/build_bazel_rules_apple/apple/internal/aspects/swift_dynamic_framework_aspect.bzl", line 110, column 35, in _swift_dynamic_framework_aspect_impl
		arch = _swift_arch_for_dep(dep)
	File "/private/var/tmp/_bazel_steeve/b4a34956aa658299157bf277e2fcd081/external/build_bazel_rules_apple/apple/internal/aspects/swift_dynamic_framework_aspect.bzl", line 68, column 35, in _swift_arch_for_dep
		target = _swift_target_for_dep(dep)
	File "/private/var/tmp/_bazel_steeve/b4a34956aa658299157bf277e2fcd081/external/build_bazel_rules_apple/apple/internal/aspects/swift_dynamic_framework_aspect.bzl", line 64, column 9, in _swift_target_for_dep
		fail("error: Expected at least one Swift compilation action for target {}.".format(dep.label))
Error in fail: error: Expected at least one Swift compilation action for target @io_sentry_sentry//:Sentry.
```

In this case, here's what I have:
```python
apple_dynamic_framework_import(
    name = "Sentry",
    framework_imports = glob(["Sentry.framework/**"]),
)

swift_library(
    name = "XXX",
    srcs = glob(["Sources/**/*.swift"]),
    visibility = ["//visibility:public"],
    deps = [
        "@io_sentry_sentry//:Sentry",
    ],
    alwayslink = True,
)
```

Indeed, since there is no compilation happening, when trying to generate `SwiftDynamicFrameworkInfo` (not sure why it needs to do that), it fails because there is no `SwiftCompile` in this target.

AFAICT, the tests are only testing against import via `objc_library`, which may be reason why they are passing.

**Comment by steeve** [comment]
cc @mccorkill1

**Comment by steeve** [comment]
I think the aspect needs to discard targets expressing the `AppleFrameworkImportInfo` provider.

**Comment by steeve** [comment]
Actually, I have a case where the dependency is an `objc_library`.

**Comment by mccorkill1** [comment]
Looking into this now. Discarding the targets expressing the `AppleFrameworkImportInfo` provider seems like a good approach to solve the problem.

**Comment by steeve** [comment]
Thanks. Unfortunately, the error trigered on a `objc_library` target, too :(

**Comment by mccorkill1** [comment]
I think this PR should solve the problem. Can you test in your environment and confirm it works? https://github.com/bazelbuild/rules_apple/pull/1035
