### ISSUE TITLE
rules_apple broken with Head Deps on buildkite

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_apple#1340]
Example failure: https://buildkite.com/bazel/rules-apple-darwin/builds/5024#cb777fda-3692-4885-a52a-feb7705c6570

failure snippet:
```
ERROR: /private/var/tmp/_bazel_buildkite/ac1b9f4ad6595c76ecdd4230b0b96e62/execroot/build_bazel_rules_apple/_tmp/827b6c71ec96c0b6cbc0432118bc3cfe/workspace/WORKSPACE:56:25: fetching http_archive rule //external:rules_proto: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/ac1b9f4ad6595c76ecdd4230b0b96e62/execroot/build_bazel_rules_apple/_tmp/827b6c71ec96c0b6cbc0432118bc3cfe/_bazel_buildkite/ceff78894d3fdbcf6d61c4521f571e52/external/bazel_tools/tools/build_defs/repo/http.bzl", line 122, column 10, in _http_archive_impl
		patch(ctx, auth = auth)
	File "/private/var/tmp/_bazel_buildkite/ac1b9f4ad6595c76ecdd4230b0b96e62/execroot/build_bazel_rules_apple/_tmp/827b6c71ec96c0b6cbc0432118bc3cfe/_bazel_buildkite/ceff78894d3fdbcf6d61c4521f571e52/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 167, column 22, in patch
		ctx.patch(patchfile, strip)
Error in patch: Unable to load package for @build_bazel_rules_swift//third_party/rules_proto:rules_proto.patch: BUILD file not found in directory 'third_party/rules_proto' of external repository @build_bazel_rules_swift. Add a BUILD file to a directory to mark it as a package.
ERROR: Skipping '//app:app': no such package '@rules_proto//proto': Unable to load package for @build_bazel_rules_swift//third_party/rules_proto:rules_proto.patch: BUILD file not found in directory 'third_party/rules_proto' of external repository @build_bazel_rules_swift. Add a BUILD file to a directory to mark it as a package.
```

**Comment by thii** [comment]
Fixed by https://github.com/bazelbuild/rules_swift/pull/754
