### ISSUE TITLE
`swift_intent_library` fails with `--remote_download_minimal`

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_apple#1409]
//:SampleIntentSwift

```
load("@build_bazel_rules_apple//apple:resources.bzl", "swift_intent_library")

swift_intent_library(
    name = "SampleIntentSwift",
    src = "@build_bazel_rules_apple//test/testdata/resources:intent.intentdefinition",
)
```

```
bazel build --remote_download_minimal //:SampleIntentSwift
```

```
ERROR: /Users/thi/dev/forks/rules_apple/BUILD:29:21: IntentGenerate SampleIntentSwift.Intent.swift failed: (Exit 1): xctoolrunner failed: error executing command
  (cd /private/var/tmp/_bazel_thi/922c5b562978cc60fc0031b402a8e8dd/execroot/build_bazel_rules_apple && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=12.1 \
    XCODE_VERSION_OVERRIDE=13.2.1.13C100 \
  bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/tools/xctoolrunner/xctoolrunner intentbuilderc generate -input '[ABSOLUTE]test/testdata/resources/intent.intentdefinition' -language Swift -classPrefix '' -swiftVersion '' -visibility '' -swift_output_src bazel-out/darwin_arm64-fastbuild/bin/SampleIntentSwift.Intent.swift)
# Configuration: 5d1541f1b42e9a39605e90f9c77c0f0922e9b35532a211c01426cc31d22da8cb
# Execution platform: @local_config_platform//:host
Traceback (most recent call last):
  File "bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/tools/xctoolrunner/xctoolrunner", line 392, in <module>
    Main()
  File "bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/tools/xctoolrunner/xctoolrunner", line 292, in Main
    module_space = FindModuleSpace()
  File "bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/tools/xctoolrunner/xctoolrunner", line 122, in FindModuleSpace
    raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
AssertionError: Cannot find .runfiles directory for bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/tools/xctoolrunner/xctoolrunner
Target //:SampleIntentSwift failed to build
INFO: Elapsed time: 0.524s, Critical Path: 0.35s
INFO: 12 processes: 11 internal, 1 local.
FAILED: Build did NOT complete successfully
```

Likely a Bazel bug but filing here to see if there is any workaround for this use case.

**Comment by jszumski** [comment]
I can reproduce this but don't know of a workaround.

**Comment by brentleyjones** [comment]
We probably aren't referencing `xctoolrunner` correctly, in order to get its runfiles setup.

**Comment by jszumski** [comment]
Fixed by https://github.com/bazelbuild/rules_apple/pull/1923?
