### ISSUE TITLE
[Remote exec] "Cannot find .runfiles directory" for `IntentGenerate` 

### ISSUE THREAD

**Issue by jerrymarino** [bazelbuild/rules_apple#1921]
Hello! I'm building some iOS apps that use rules_apple for bundling with buildfarm and remote execution. I'm hitting an error with `IntentGenerate` unfortunately. I was able to replicate this by building the application where the `--remote_executor` argument is set to bazel-buildfarm 's GRPC endpoint.

```
ERROR: /Users/jmarino/Development/rules_ios/tests/ios/frameworks/intentdefinition/BUILD.bazel:13:16: IntentGenerate tests/ios/frameworks/intentdefinition/SwiftIntentConsumer_Intents.intentdefinition_gen.swift failed: (Exit 1): xctoolrunner failed: error executing command (from target //tests/ios/frameworks/intentdefinition:SwiftIntentConsumer_Intents.intentdefinition_gen)
  (cd /private/var/tmp/_bazel_jmarino/4180ce3012e050416efacbaebca2f601/execroot/build_bazel_rules_ios && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=16.2 \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
  bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-103902c0b028/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner intentbuilderc generate -input '[ABSOLUTE]tests/ios/frameworks/intentdefinition/Intents.intentdefinition' -language Swift -classPrefix '' -swiftVersion '' -visibility '' -swift_output_src bazel-out/ios-sim_arm64-min12.0-applebin_ios-ios_sim_arm64-dbg-ST-92176b08c341/bin/tests/ios/frameworks/intentdefinition/SwiftIntentConsumer_Intents.intentdefinition_gen.swift)
# Configuration: 679b9657b8bf79ae56a262b555c6b5dfd2d17000ce1f4c1e4eb368f2b33d66d6
# Execution platform: @local_config_platform//:host
Traceback (most recent call last):
  File "/private/tmp/worker/shard/operations/76cbd62b-0af9-43d4-8038-60cb406763e1/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-103902c0b028/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner", line 541, in <module>
    Main()
  File "/private/tmp/worker/shard/operations/76cbd62b-0af9-43d4-8038-60cb406763e1/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-103902c0b028/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner", line 442, in Main
    module_space = FindModuleSpace(main_rel_path)
  File "/private/tmp/worker/shard/operations/76cbd62b-0af9-43d4-8038-60cb406763e1/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-103902c0b028/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner", line 172, in FindModuleSpace
    raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
AssertionError: Cannot find .runfiles directory for bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-103902c0b028/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner

```

**Comment by brentleyjones** [comment]
I look at this tomorrow morning. Thanks for the report!

**Comment by brentleyjones** [comment]
I reproduced locally, and https://github.com/bazelbuild/rules_apple/pull/1923 fixes this.
