### ISSUE TITLE
Error: 'struct' value has no field or method 'objc' with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_apple#2020]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3171#0189619a-63fd-418f-bdbe-d5293ad3138f

Platform : MacOS

Logs : 
```
ERROR: /Users/buildkite/builds/bk-imacpro-7/bazel-downstream-projects/rules_apple/test/starlark_tests/targets_under_test/apple/BUILD:990:25: in apple_static_xcframework rule //test/starlark_tests/targets_under_test/apple:ios_static_xcfmwk_with_objc_sdk_dylibs_and_and_sdk_frameworks:
Traceback (most recent call last):
	File "/Users/buildkite/builds/bk-imacpro-7/bazel-downstream-projects/rules_apple/apple/internal/xcframework_rules.bzl", line 903, column 73, in _apple_static_xcframework_impl
		link_result = linking_support.register_static_library_linking_action(ctx = ctx)
	File "/Users/buildkite/builds/bk-imacpro-7/bazel-downstream-projects/rules_apple/apple/internal/linking_support.bzl", line 256, column 31, in _register_static_library_linking_action
		objc = linking_outputs.objc,
Error: 'struct' value has no field or method 'objc'
Available attributes: output_groups, outputs
(04:11:34) ERROR: /Users/buildkite/builds/bk-imacpro-7/bazel-downstream-projects/rules_apple/test/starlark_tests/targets_under_test/apple/BUILD:990:25: Analysis of target '//test/starlark_tests/targets_under_test/apple:ios_static_xcfmwk_with_objc_sdk_dylibs_and_and_sdk_frameworks' failed
(04:11:34) ERROR: Analysis of target '//test/starlark_tests:apple_static_xcframework_objc_generated_modulemap_file_content_test' failed; build aborted: Analysis failed
```

Steps :  
```
git clone https://github.com/bazelbuild/rules_apple.git
git reset 4b4f645b75ba1df7e70244b696151bb2172ac8f2 --hard
export USE_BAZEL_VERSION=7060f6fc79da582479aacb528bffa96f51c5a98e
bazel build tools/... test/...
```

Culprit : https://github.com/bazelbuild/bazel/commit/426f2254669f62b7d332094a0af6d4dc6200ad51

CC Greenteam @mai93

**Comment by mai93** [comment]
@keith Tracking bug for this change: https://github.com/bazelbuild/bazel/issues/17377
