### ISSUE TITLE
Error in new_objc_provider: Key 'linkopt' no longer supported in ObjcProvider


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_apple#2353]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3575#018ce73b-14e1-4fb3-80d1-dd333ede35b2
Platform: MacOS

 Logs: 
```
(05:01:58) ERROR: /private/var/tmp/_bazel_buildkite/79edcf2dae0ace64ac8fec4fc8c87a0c/external/rules_swift~1.13.0~non_module_deps~build_bazel_rules_swift_local_config/BUILD:9:22: in xcode_swift_toolchain rule @@rules_swift~1.13.0~non_module_deps~build_bazel_rules_swift_local_config//:toolchain:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/79edcf2dae0ace64ac8fec4fc8c87a0c/external/rules_swift~1.13.0/swift/internal/xcode_swift_toolchain.bzl", line 580, column 57, in _xcode_swift_toolchain_impl
		swift_linkopts_providers = _swift_linkopts_providers(
	File "/private/var/tmp/_bazel_buildkite/79edcf2dae0ace64ac8fec4fc8c87a0c/external/rules_swift~1.13.0/swift/internal/xcode_swift_toolchain.bzl", line 256, column 51, in _swift_linkopts_providers
		objc_info = apple_common.new_objc_provider(linkopt = depset(linkopts)),
Error in new_objc_provider: Key 'linkopt' no longer supported in ObjcProvider (use CcInfo instead).
```

 Steps:
```
 git clone https://github.com/bazelbuild/rules_apple.git 
 git reset 5574843206b3adab9fd0ef8ab57064379ff9cf31 --hard
export USE_BAZEL_VERSION=8e8ddaba0e90c280bfd85644d6ccd91df5b6d353
bazel build tools/... test/... 
```

 CC Greenteam @fweikert

**Comment by sgowroji** [comment]
Hi @keith, Latest CI is still shows failure  [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3583#018cf658-a8fd-4bc7-8a47-b29dd8d9bd6d](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3583#018cf658-a8fd-4bc7-8a47-b29dd8d9bd6d) for rules\_apple.  Can you please take a  look. Thanks!

**Comment by keith** [comment]
thanks, fixed by https://github.com/bazelbuild/rules_apple/pull/2359

**Comment by sgowroji** [comment]
Great !! Thanks for the immediate response and fix.
