### ISSUE TITLE
Error in new_objc_provider: Key 'linkopt' no longer supported in ObjcProvider 


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_apple#2370]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3601#018d1fae-28a5-47c5-a1be-881bc1594610

 Platform: MacOS

 Logs: 
```ERROR: /Users/buildkite/builds/bk-imacpro-18/bazel-org-repo-root/rules_apple/test/starlark_tests/targets_under_test/macos/BUILD:2395:31: in macos_command_line_launchdplist rule //test/starlark_tests/targets_under_test/macos:cmd_app_info_and_launchd_plists.merged_launchdplists:
Traceback (most recent call last):
	File "/Users/buildkite/builds/bk-imacpro-18/bazel-org-repo-root/rules_apple/apple/internal/macos_binary_support.bzl", line 253, column 52, in _macos_command_line_launchdplist_impl
		return linking_support.sectcreate_objc_provider(
	File "/Users/buildkite/builds/bk-imacpro-18/bazel-org-repo-root/rules_apple/apple/internal/linking_support.bzl", line 102, column 39, in _sectcreate_objc_provider
		apple_common.new_objc_provider(
Error in new_objc_provider: Key 'linkopt' no longer supported in ObjcProvider (use CcInfo instead).
(04:18:15) ERROR: /Users/buildkite/builds/bk-imacpro-18/bazel-org-repo-root/rules_apple/test/starlark_tests/targets_under_test/macos/BUILD:2395:31: Analysis of target '//test/starlark_tests/targets_under_test/macos:cmd_app_info_and_launchd_plists.merged_launchdplists' failed
(04:18:15) ERROR: Analysis of target '//test/starlark_tests/targets_under_test/macos:cmd_app_info_and_launchd_plists.merged_launchdplists' failed; build aborted
```
 Culprit Found: https://github.com/bazelbuild/bazel/commit/67c5c0fbf99c80aeb17073c79e8017bde443fd4b, https://github.com/bazelbuild/bazel/commit/48eb0236b2f65babf3dd9c314069774a78b629a3

 Steps:
```
git clone https://github.com/bazelbuild/rules_apple.git 
git reset ed073e3ea4cd4ab3cd80bb5ecc60b11c21fed400 --hard
export USE_BAZEL_VERSION=416333dcca2e48e430df4ff54a9e3f163078baf2
bazel build --config=visionos tools/... test/... 
```
 CC Greenteam @meteorcloudy

**Comment by comius** [comment]
cc @keith
