### ISSUE TITLE
[Bazel CI] FATAL: Unrecoverable error while evaluating node '//apple/internal:environment_plist_ios'


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_apple#2463]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3890#018fc7ad-aa39-4638-87f0-39a429b15ba9

 Platform: MacOS

 Logs: 
```
(06:08:18) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//apple/internal:environment_plist_ios, config=BuildConfigurationKey[6fa13f1c3cbf9f638f9e395d14c4e078ceee911a5baa4182c5e7481cf9c34571]}' (requested by nodes 'ConfiguredTargetKey{label=//test/starlark_tests/targets_under_test/ios:static_framework_with_umbrella_header_conflict, config=BuildConfigurationKey[6fa13f1c3cbf9f638f9e395d14c4e078ceee911a5baa4182c5e7481cf9c34571]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:557)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:426)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: IllegalArgumentException thrown during Starlark evaluation (//apple/internal:environment_plist_ios)
	at <starlark>.multi_arch_platform(<builtin>:0)
	at <starlark>._platform_prerequisites(/Users/buildkite/builds/bk-macstudio-1/bazel-org-repo-root/rules_apple/apple/internal/platform_support.bzl:96)
	at <starlark>._environment_plist_impl(/Users/buildkite/builds/bk-macstudio-1/bazel-org-repo-root/rules_apple/apple/internal/environment_plist.bzl:52)
Caused by: java.lang.IllegalArgumentException: Expected post-split-transition platform type ios to match input ios
	at com.google.devtools.build.lib.rules.apple.AppleConfiguration.getMultiArchitectures(AppleConfiguration.java:280)
	at com.google.devtools.build.lib.rules.apple.AppleConfiguration.getMultiArchPlatform(AppleConfiguration.java:326)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:178)
	at net.starlark.java.eval.BuiltinFunction.fastcall(BuiltinFunction.java:78)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:699)
	at net.starlark.java.eval.Eval.eval(Eval.java:514)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:121)
	at net.starlark.java.eval.Eval.exec(Eval.java:285)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:203)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:699)
	at net.starlark.java.eval.Eval.eval(Eval.java:514)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:121)
	at net.starlark.java.eval.Eval.exec(Eval.java:285)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:203)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleConfiguredTargetUtil.evalRule(StarlarkRuleConfiguredTargetUtil.java:100)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:387)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:203)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1352)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:389)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:313)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:468)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:426)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
bazel build failed with exit code 37
🚨 Error: The command exited with status 1
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_apple
git reset f81ef63b220b1d094379cdc68a53e635ad9ac5f4  --hard
export USE_BAZEL_VERSION=00a0837f86d6086bba4bbcfdb6ab354edb7f3b63
bazel buiild -- tools/... test/... 
 ``` 
 CC Greenteam @comius

**Comment by brentleyjones** [comment]
Reported here: https://github.com/bazelbuild/bazel/commit/8e783b065c66c005db26d85e9ec6e8e28c42b2f2#commitcomment-142514435

**Comment by sgowroji** [comment]
Closing it as the CI is green now in Downstream.
