### ISSUE TITLE
Bazel 8 crash when building `ios_application` at the root

### ISSUE THREAD

**Issue by jpsim** [bazelbuild/rules_apple#2619]
The iOS app tutorial at [doc/tutorials/ios-app.md](https://github.com/bazelbuild/rules_apple/blob/master/doc/tutorials/ios-app.md) currently fails to build with Bazel 8.0.0 with the following crash:

```console
$ bazel build //:iOSApp
Analyzing: target //:iOSApp (28 packages loaded, 553 targets configured)
    currently loading: @@rules_python+//python/private

FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//:iOSApp, config=BuildConfigurationKey[8eddf44734490dc07f46b246d49780b061f129833bf45d4750c99942b5c6ace7]}' (requested by nodes 'ConfiguredTargetKey{label=//:iOSApp, config=BuildConfigurationKey[e5d0b45255bbe29fcc274b3efed42ccbd4b88bf8d5a015d3138aed480339a787]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:547)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: IllegalArgumentException thrown during Starlark evaluation (//:iOSApp)
	at <starlark>.declare_shareable_artifact(<builtin>:0)
	at <starlark>._register_configuration_specific_link_actions(/virtual_builtins_bzl/common/objc/compilation_support.bzl:858)
	at <starlark>._link_multi_arch_binary(/private/var/tmp/_bazel_jsimard/91c5c0ba17ff5874fc856288746ea05f/external/rules_apple+/apple/internal/linking_support.bzl:300)
	at <starlark>._register_binary_linking_action(/private/var/tmp/_bazel_jsimard/91c5c0ba17ff5874fc856288746ea05f/external/rules_apple+/apple/internal/linking_support.bzl:528)
	at <starlark>._ios_application_impl(/private/var/tmp/_bazel_jsimard/91c5c0ba17ff5874fc856288746ea05f/external/rules_apple+/apple/internal/ios_rules.bzl:239)
Caused by: java.lang.IllegalArgumentException: /iOSApp_bin
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.google.devtools.build.lib.actions.ArtifactFactory.validatePath(ArtifactFactory.java:183)
	at com.google.devtools.build.lib.actions.ArtifactFactory.getDerivedArtifact(ArtifactFactory.java:227)
	at com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment.getDerivedArtifact(CachingAnalysisEnvironment.java:282)
	at com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment.getDerivedArtifact(CachingAnalysisEnvironment.java:274)
	at com.google.devtools.build.lib.analysis.RuleContext.getShareableArtifact(RuleContext.java:716)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkActionFactory.createShareableArtifact(StarlarkActionFactory.java:1023)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:178)
	at net.starlark.java.eval.BuiltinFunction.fastcall(BuiltinFunction.java:78)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:699)
	at net.starlark.java.eval.Eval.eval(Eval.java:514)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:121)
	at net.starlark.java.eval.Eval.exec(Eval.java:285)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execIf(Eval.java:224)
	at net.starlark.java.eval.Eval.exec(Eval.java:300)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:699)
	at net.starlark.java.eval.Eval.eval(Eval.java:514)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:121)
	at net.starlark.java.eval.Eval.exec(Eval.java:285)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFor(Eval.java:138)
	at net.starlark.java.eval.Eval.exec(Eval.java:293)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:699)
	at net.starlark.java.eval.Eval.eval(Eval.java:514)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:121)
	at net.starlark.java.eval.Eval.exec(Eval.java:285)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:699)
	at net.starlark.java.eval.Eval.eval(Eval.java:514)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:121)
	at net.starlark.java.eval.Eval.exec(Eval.java:285)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:208)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:807)
	at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleConfiguredTargetUtil.evalRule(StarlarkRuleConfiguredTargetUtil.java:100)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:405)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:202)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:1389)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:447)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

Bazel 7.4.1 works fine:

```console
$ USE_BAZEL_VERSION=7.4.1 bazel build //:iOSApp
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:iOSApp (127 packages loaded, 1110 targets configured).
INFO: Found 1 target...
Target //:iOSApp up-to-date:
  bazel-bin/iOSApp.ipa
INFO: Elapsed time: 20.834s, Critical Path: 7.11s
INFO: 73 processes: 45 internal, 26 darwin-sandbox, 1 local, 1 worker.
INFO: Build completed successfully, 73 total actions
```

I also found that if the ios_application is not at the root then this crash doesn't occur: e.g. `//foo:iOSApp`

**Comment by brentleyjones** [comment]
Looks like a Bazel bug.

**Comment by jpsim** [comment]
Reported on Bazel GitHub issues now too: https://github.com/bazelbuild/bazel/issues/24625

Feel free to close this if you want.
