### ISSUE TITLE
Entitlements validation fails for associated-domains

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#292]
After this commit: https://github.com/bazelbuild/rules_apple/pull/291/commits/18a02c39b324ce4a3c8ea69e4d5a3a8cb9d8c2d5

We're seeing this failure on our project:

```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_ksmiley/14f65abacd188fa449c6544ca07ee7f6/execroot/lyftios/bazel-out/host/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool.runfiles/build_bazel_rules_apple/tools/plisttool/plisttool.py", line 1437, in <module>
    _main(sys.argv[1])
  File "/private/var/tmp/_bazel_ksmiley/14f65abacd188fa449c6544ca07ee7f6/execroot/lyftios/bazel-out/host/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool.runfiles/build_bazel_rules_apple/tools/plisttool/plisttool.py", line 1425, in _main
    tool.run()
  File "/private/var/tmp/_bazel_ksmiley/14f65abacd188fa449c6544ca07ee7f6/execroot/lyftios/bazel-out/host/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool.runfiles/build_bazel_rules_apple/tools/plisttool/plisttool.py", line 1381, in run
    t.validate_plist(out_plist)
  File "/private/var/tmp/_bazel_ksmiley/14f65abacd188fa449c6544ca07ee7f6/execroot/lyftios/bazel-out/host/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool.runfiles/build_bazel_rules_apple/tools/plisttool/plisttool.py", line 1062, in validate_plist
    plist, warn_only=(validation_mode == 'warn'))
  File "/private/var/tmp/_bazel_ksmiley/14f65abacd188fa449c6544ca07ee7f6/execroot/lyftios/bazel-out/host/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool.runfiles/build_bazel_rules_apple/tools/plisttool/plisttool.py", line 1171, in _validate_entitlements_against_profile
    supports_wildcards=True)
  File "/private/var/tmp/_bazel_ksmiley/14f65abacd188fa449c6544ca07ee7f6/execroot/lyftios/bazel-out/host/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool.runfiles/build_bazel_rules_apple/tools/plisttool/plisttool.py", line 1268, in _check_entitlements_array
    assert '*' not in src_grp
```

With these associated domains:

```
<key>com.apple.developer.associated-domains</key>
<array>
    <string>applinks:lyft.com</string>
    <string>applinks:*.lyft.com</string>
</array>
```

Based on the new call setting `supports_wildcards=True` I assume these should be valid (they also work correctly).

**Comment by keith** [comment]
So it looks like while this is in our entitlements files, in our provisioning profile is just a `*`. Let me see what a final `.ipa` has

**Comment by thomasvl** [comment]
Supports wildcards also was built around reverse dns, and the test only checked for '"*"', so something like '"*.lyft.com"' isn't going to be handled by the current wildcard code.

@dierksen fyi

**Comment by keith** [comment]
Thee final binary's entitlements are correctly set to the ones from our entitlements files:

```
$ codesign -d --entitlements - Lyft.app/Lyft
qq<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
...
        <array>
                <string>applinks:lyft.com</string>
                <string>applinks:*.lyft.com</string>
        </array>
        ...
</dict>
</plist>
```

**Comment by thomasvl** [comment]
Ah, so wildcard support is just about wildcards in the profile, not in the entitlements.  Looks like we need two things fixed:

1. associated domains allows `*` in the entitlements.
1. the wildcard support for associated domains likely needs to deal with things that aren't reverse dns.

**Comment by thomasvl** [comment]
Re 2 - looks like Apple's portal only makes it a boolean for wildcard support, so the fact that we're using reverse dns here doesn't matter as the profile should only ever have _"*"_ and never _"*.some.com"_.
