### ISSUE TITLE
Tulsi fails loading ios.bzl

### ISSUE THREAD

**Issue by lswith** [bazelbuild/rules_apple#53]
```
[5:35:55 pm](0): Bazel command info:
"/Users/lswithenbank/Code/bazel-master/bazel" "--max_idle_secs=60" "query" "--announce_rc" "--noimplicit_deps" "--order_output=no" "--noshow_loading_progress" "--noshow_progress" "kind(rule, FLKeychain:all)" "--output" "xml"
Exited with code 7

Another command is running (pid = 29971).  Waiting for it to complete...
Another command (pid=29971) is running.  Waiting for it to complete...
____Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
ERROR: /private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl:114:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 114
		merge_dictionaries(common_rule_attributes(), {"app_ic...))})
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 114, in merge_dictionaries
		common_rule_attributes()
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/rule_attributes.bzl", line 217, in common_rule_attributes
		merge_dictionaries(_tool_attributes(), simple_path_fo...(), ..., <2 more arguments>), "bundle_id": attr.string(mandatory = True), "infoplists": attr.label_list(allow_files = [".plist"], mandator..., ...), "ipa_post_processor": attr.label(allow_files = True, executable = T..., ..."), "minimum_os_version": attr.string(mandatory = False), "provisioning_profile": attr.label(allow_files = [".mobileprovision...], ...), "strings": attr.label_list(allow_files = [".strings"]), "_propagates_frameworks": attr.bool(default = False), "_requires_signing_for_device": attr.bool(default = True), "_skip_signing": attr.bool(default = False)})
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/rule_attributes.bzl", line 221, in merge_dictionaries
		attr.label(aspects = [apple_bundling_aspect..., <2 more arguments>)
Illegal argument: element in 'providers' is of unexpected type. Should be list of string, but got provider. Notice: one single list of string as 'providers' is still supported..
ERROR: /private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl:157:13: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 155
		rule(_ios_application_impl, attrs = _IO..., <3 more arguments>)
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 157, in rule
		_IOS_APPLICATION_ATTRIBUTES
name '_IOS_APPLICATION_ATTRIBUTES' is not defined.
ERROR: /private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl:195:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 195
		merge_dictionaries(common_rule_attributes(), {"app_ic...)})
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 195, in merge_dictionaries
		common_rule_attributes()
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/rule_attributes.bzl", line 217, in common_rule_attributes
		merge_dictionaries(_tool_attributes(), simple_path_fo...(), ..., <2 more arguments>), "bundle_id": attr.string(mandatory = True), "infoplists": attr.label_list(allow_files = [".plist"], mandator..., ...), "ipa_post_processor": attr.label(allow_files = True, executable = T..., ..."), "minimum_os_version": attr.string(mandatory = False), "provisioning_profile": attr.label(allow_files = [".mobileprovision...], ...), "strings": attr.label_list(allow_files = [".strings"]), "_propagates_frameworks": attr.bool(default = False), "_requires_signing_for_device": attr.bool(default = True), "_skip_signing": attr.bool(default = False)})
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/rule_attributes.bzl", line 221, in merge_dictionaries
		attr.label(aspects = [apple_bundling_aspect..., <2 more arguments>)
Illegal argument: element in 'providers' is of unexpected type. Should be list of string, but got provider. Notice: one single list of string as 'providers' is still supported..
ERROR: /private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl:229:13: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 227
		rule(_ios_extension_impl, attrs = _IOS_..., <2 more arguments>)
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 229, in rule
		_IOS_EXTENSION_ATTRIBUTES
name '_IOS_EXTENSION_ATTRIBUTES' is not defined.
ERROR: /private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl:265:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 265
		merge_dictionaries(common_rule_attributes(), {"binary..., <3 more arguments>), "hdrs": attr.label_list(allow_files = [".h"]), "families": attr.string_list(mandatory = True), "linkopts": attr.string_list(), "_allowed_families": attr.string_list(default = ["iphone", "ipad"]), "_bundle_extension": attr.string(default = ".framework"), "_needs_pkginfo": attr.bool(default = False), "_path_in_archive_format": attr.string(default = "%s"), "_platform_type": attr.string(default = str(apple_common.platf...)), "_propagates_frameworks": attr.bool(default = True), "_skip_signing": attr.bool(default = True)})
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 265, in merge_dictionaries
		common_rule_attributes()
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/rule_attributes.bzl", line 217, in common_rule_attributes
		merge_dictionaries(_tool_attributes(), simple_path_fo...(), ..., <2 more arguments>), "bundle_id": attr.string(mandatory = True), "infoplists": attr.label_list(allow_files = [".plist"], mandator..., ...), "ipa_post_processor": attr.label(allow_files = True, executable = T..., ..."), "minimum_os_version": attr.string(mandatory = False), "provisioning_profile": attr.label(allow_files = [".mobileprovision...], ...), "strings": attr.label_list(allow_files = [".strings"]), "_propagates_frameworks": attr.bool(default = False), "_requires_signing_for_device": attr.bool(default = True), "_skip_signing": attr.bool(default = False)})
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/rule_attributes.bzl", line 221, in merge_dictionaries
		attr.label(aspects = [apple_bundling_aspect..., <2 more arguments>)
Illegal argument: element in 'providers' is of unexpected type. Should be list of string, but got provider. Notice: one single list of string as 'providers' is still supported..
ERROR: /private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl:302:13: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 300
		rule(_ios_framework_impl, attrs = _IOS_..., <2 more arguments>)
	File "/private/var/tmp/_bazel_lswithenbank/a36946a2b8731dcc3591b08e68f5ca48/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 302, in rule
		_IOS_FRAMEWORK_ATTRIBUTES
name '_IOS_FRAMEWORK_ATTRIBUTES' is not defined.
ERROR: while parsing 'FLKeychain:all': error loading package 'FLKeychain': Extension file 'apple/bundling/ios_rules.bzl' has errors.
```

**Comment by sergiocampama** [comment]
So in order to use the head version of the rules, you'll need to get a head version of bazel. You'll need to track github.com/bazelbuild/bazel and run `bazel build src:bazel` (I believe that's the right command, it should build bazel from source with the currently installed bazel)

Finally copy the output of that command into a folder in $PATH and you should be able to use the rules again.

This should become unnecessary once the next release of bazel comes out.

**Comment by lswith** [comment]
yep can confirm it works with the latest version of bazel (1a57d298f8aa6ea8136d93223902104f2479cd2a)
