### ISSUE TITLE
macos_application fails under --incompatible_run_shell_command_string

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/rules_apple#736]
ctx.actions.run command needs to be a string, but is a list somewhere in rules_apple.

**Comment by thomasvl** [comment]
There's a bug against bazel for the case this has to be done.  It still hasn't been fixed in bazel.

**Comment by anhappdev** [comment]
I still have this error:
```
ERROR: /private/var/tmp/_bazel_anh/210e4ef5344cc25a66ffe81bcef839e5/external/build_bazel_rules_apple/tools/realpath/BUILD:9:14: in _apple_genrule_inner rule @build_bazel_rules_apple//tools/realpath:realpath_genrule:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_anh/210e4ef5344cc25a66ffe81bcef839e5/external/build_bazel_apple_support/rules/apple_genrule.bzl", line 78, column 28, in _apple_genrule_impl
		apple_support.run_shell(
	File "/private/var/tmp/_bazel_anh/210e4ef5344cc25a66ffe81bcef839e5/external/build_bazel_apple_support/lib/apple_support.bzl", line 339, column 26, in _run_shell
		ctx.actions.run_shell(**_kwargs_for_apple_platform(ctx, **kwargs))
Error in run_shell: 'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_run_shell_command_string=false.
```

Running on a Mac M1 with
```
$ bazel --version
bazel 4.2.1-homebrew
```

Set `--incompatible_run_shell_command_string=false` may be a workaround but not an optimal solution.

**Comment by keith** [comment]
Are you using the most recent release of the rules?

**Comment by keith** [comment]
It doesn't seem that you are, the callstack above mentions `realpath` which was removed 2 years ago https://github.com/bazelbuild/rules_apple/commit/cf00aaff1f31bb3284760acd48b8a5aa19a9e1d8

Could you have another repository overriding the version you're specifying in your WORKSPACE?

**Comment by anhappdev** [comment]
Yes. You are right. I use TensorFlow and they have another version. I can remove the `build_bazel_rules_apple` from my `WORKSPACE` and still get the error. Thanks for the explanation.
