### ISSUE TITLE
Unable to pass env variables to ios_unit_test that contain spaces

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [bazelbuild/rules_apple#937]
Hello There!

I am running into an issue running an `ios_unit_test` with env variables that contain spaces. Here is my build rule:

```
ios_unit_test(
    name = "MySnapshotTests",
    minimum_os_version = "13.0",
    deps = [
        ":MySnapshotTestsLib"
    ],
    test_host = "//Infra/TestHost:SnapshotTestHostApp",
    env = {
        "FB_REFERENCE_IMAGE_DIR": "/My Project/Snapshot/ReferenceImages",
        "IMAGE_DIFF_DIR": "/My Project/Snapshot/FailureDiffs"
    }
)
```

If I run this I get this error:

`
2020-10-08 21:23:50,062 Will consider the test as test type xctest to run.
2020-10-08 21:23:50,063 Generating xctestrun file.
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "../xctestrunner/file/downloaded/__main__.py", line 329, in <module>
  File "../xctestrunner/file/downloaded/__main__.py", line 323, in main
  File "../xctestrunner/file/downloaded/__main__.py", line 220, in _SimulatorTest
  File "../xctestrunner/file/downloaded/__main__.py", line 162, in _RunSimulatorTest
  File "../xctestrunner/file/downloaded/__main__.py", line 270, in _GetJson
xctestrunner.shared.ios_errors.IllegalArgumentError: Expecting , delimiter: line 1 column 106 (char 105)
`

I have seen other issue tickets that have dealt with spacing issues in rules_apple. Is this an issue that we need to fix in rules_apple or is there another way to tackle this?

Thanks!

**Comment by keith** [comment]
I haven't noticed this but it sounds very plausible given how env vars are handled:

https://github.com/bazelbuild/rules_apple/blob/5819dc78d9233dce35d546f7a69690f075bbf1e5/apple/testing/default_runner/ios_test_runner.template.sh#L94-L103

Fixing this and adding a test shouldn't be too bad

**Comment by tinder-maxwellelliott** [comment]
I will take a look!
