### ISSUE TITLE
Bundle large static framework failed

### ISSUE THREAD

**Issue by aaaron7** [bazelbuild/rules_apple#970]
When bundle an iOS static framework which contains 3 archs(arm64, armv7, x86_64). bazel failed with following error stack:

```
ERROR: /Users/aaron/Documents/projects/gitlab/uPipe/BUILD:20:21: Bundling uPipeFramework failed (Exit 1) bundletool failed: error executing command bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool bazel-out/darwin-opt/bin/uPipeFramework-intermediates/bundletool_control.json

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_aaron/2e3fa25f9dde28a2194ff7ff3b8d75c4/sandbox/darwin-sandbox/377/execroot/mediapipe/bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool.runfiles/build_bazel_rules_apple/tools/bundletool/bundletool.py", line 237, in <module>
    _main(sys.argv[1])
  File "/private/var/tmp/_bazel_aaron/2e3fa25f9dde28a2194ff7ff3b8d75c4/sandbox/darwin-sandbox/377/execroot/mediapipe/bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool.runfiles/build_bazel_rules_apple/tools/bundletool/bundletool.py", line 225, in _main
    bundler.run()
  File "/private/var/tmp/_bazel_aaron/2e3fa25f9dde28a2194ff7ff3b8d75c4/sandbox/darwin-sandbox/377/execroot/mediapipe/bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool.runfiles/build_bazel_rules_apple/tools/bundletool/bundletool.py", line 117, in run
    f.get('contents_only', False), out_zip)
  File "/private/var/tmp/_bazel_aaron/2e3fa25f9dde28a2194ff7ff3b8d75c4/sandbox/darwin-sandbox/377/execroot/mediapipe/bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool.runfiles/build_bazel_rules_apple/tools/bundletool/bundletool.py", line 154, in _add_files
    self._write_entry(dest, f.read(), fexec, out_zip)
  File "/private/var/tmp/_bazel_aaron/2e3fa25f9dde28a2194ff7ff3b8d75c4/sandbox/darwin-sandbox/377/execroot/mediapipe/bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool.runfiles/build_bazel_rules_apple/tools/bundletool/bundletool.py", line 216, in _write_entry
    out_zip.writestr(zipinfo, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1257, in writestr
    self._writecheck(zinfo)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1137, in _writecheck
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Filesize would require ZIP64 extensions
----------------
Note: The failure of target @build_bazel_rules_apple//tools/bundletool:bundletool (with exit code 1) may have been caused by the fact that it is running under Python 2 instead of Python 3. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY3, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //:uPipeFramework failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 113.687s, Critical Path: 86.77s
INFO: 327 processes: 327 darwin-sandbox.
```

After investigating zipfile.py I found Python will raise exception if the file large than 2GB when ZIP64 not be enabled.  Turn ZIP64 on in buntool.py by add allowZip64 = True solved the problem.

```
    with zipfile.ZipFile(output_path, 'w', allowZip64 = True) as out_zip:
```

Maybe we can turn the extension on by default? I created a PR for this.

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_apple/pull/971
